##
##   88""Yb     88""Yb     88     8b    d8     88   88     .dP"Y8
##   88__dP     88__dP     88     88b  d88     88   88     `Ybo."
##   88"""      88"Yb      88     88YbdP88     Y8   8P     o.`Y8b
##   88         88  Yb     88     88 YY 88     `YbodP'     8bodP'
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## @author Chris Prime
## @link https://github.com/Chris-Prime/FactionsPE
##
name: FactionsPE
author: BlockHorizons
authors:
- Chris-Prime (@PrimusLV, @flipkris)
- Sandertv (@Sandertv)
api:
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
main: factions\FactionsPE
version: 1.0.0
softdepend: [EconomyAPI, MassiveEconomy, PocketMoney, GoldStd, PureChat, PurePerms]
loadafter: [PurePerms, PureChat]

permissions:
  factions.*:
    default: false
    description: grant all faction permissions
    children:
      factions.help: {description: see help page, default: true}
      factions.access: {description: manage access, with the proper fperm, default: true}
      factions.access.faction: {description: grant faction access, with the proper fperm, default: true}
      factions.access.player: {description: grant player access, with the proper fperm, default: true}
      factions.access.view: {description: view access, default: true}
      factions.override: {description: enable override mode, default: op}
      factions.chat: {description: chat with your faction members, default: true}
      factions.claim: {description: claim faction territory, default: true}
      factions.claim.one: {description: claim a single chunk, default: true}
      factions.claim.auto: {description: claim as you walk around, default: true}
      factions.claim.fill: {description: claim by filling, default: true}
      factions.claim.square: {description: claim by square and radius, default: true}
      factions.claim.circle: {description: claim by circle and radius, default: true}
      factions.claim.all: {description: claim all faction land, default: true}
      factions.close: {description: close faction to require invitations, default: true}
      factions.create: {description: create new faction, default: true}
      factions.description: {description: change faction description, default: true}
      factions.disband: {description: disband faction, default: true}
      factions.expansions: {description: list expansions, default: true}
      factions.faction: {description: show faction information, default: true}
      factions.flag: {description: manage faction flags, default: true}
      factions.flag.list: {description: list flags, default: true}
      factions.flag.set: {description: set flags, default: true}
      factions.flag.show: {description: show flags, default: true}
      factions.home: {description: teleport to faction home, default: true}
      factions.hud: {description: toggle hud, default: true}
      factions.invite: {description: manage invites, default: true}
      factions.invite.list: {description: list invited players, default: true}
      factions.invite.list.other: {description: list invited players of another factions, default: op}
      factions.invite.add: {description: invite player, default: true}
      factions.invite.remove: {description: revoke an invite, default: true}
      factions.join: {description: join faction, default: true}
      factions.join.others: {description: have another player join faction, default: op}
      factions.kick: {description: kick player from faction, default: true}
      factions.leave: {description: leave your faction, default: true}
      factions.list: {description: list all factions, default: true}
      factions.main: {description: access main faction command, default: true}
      factions.map: {description: show territory map, default: true}
      factions.money: {description: manage faction money, default: true}
      factions.money.balance: {description: show faction money, default: true}
      factions.money.balance.any: {description: show another factions money, default: op}
      factions.money.deposit: {description: deposit to faction, default: true}
      factions.money.f2f: {description: transfer f --> f, default: true}
      factions.money.f2p: {description: transfer f --> p, default: true}
      factions.money.p2f: {description: transfer p --> f, default: true}
      factions.money.withdraw: {description: withdraw from faction, default: true}
      factions.motd: {description: faction motd, default: true}
      factions.open: {description: set if invitation is required to join, default: true}
      factions.perm: {description: change faction permissions, default: true}
      factions.perm.list: {description: list perms, default: true}
      factions.perm.set: {description: set perms, default: true}
      factions.perm.show: {description: show perms, default: true}
      factions.player: {description: show player information, default: op}
      factions.powerboost: {description: set powerboost, default: op}
      factions.rank: {description: manage/show ranks, default: true}
      factions.rank.show: {description: show rank, default: true}
      factions.rank.action: {description: change rank, default: true}
      factions.relation: {description: manage faction relations, default: true}
      factions.relation.list: {description: list all factions with certain relation, default: true}
      factions.relation.set: {description: set relation wish to another faction, default: true}
      factions.relation.wishes: {description: list the relation wishes, default: true}
      factions.seechunk: {description: see the chunk you stand in, default: true}
      factions.sethome: {description: set the faction home, default: true}
      factions.setpower: {description: set power, default: op}
      factions.status: {description: show status, default: true}
      factions.name: {description: set faction name, default: true}
      factions.title: {description: set player title, default: op}
      factions.title.color: {description: set player title with color, default: true}
      factions.top: {description: see most powerful factions, default: true}
      factions.territorytitles: {description: toggle territory titles, default: true}
      factions.unclaim: {description: unclaim faction territory, default: true}
      factions.unclaim.one: {description: unclaim a single chunk, default: true}
      factions.unclaim.auto: {description: unclaim as you walk around, default: true}
      factions.unclaim.fill: {description: unclaim by filling, default: true}
      factions.unclaim.square: {description: unclaim by square and radius, default: true}
      factions.unclaim.circle: {description: unclaim by circle and radius, default: true}
      factions.unclaim.all: {description: unclaim all faction land, default: true}
      factions.unsethome: {description: unset faction home, default: true}
      factions.unstuck: {description: teleport to nearest wilderness, default: true}
      factions.version: {description: see plugin version, default: true}
      factions.help: {description: see list of avaliable sub-commands, default: true}
